### ISSUE TITLE
[KORREKTUR]: 25 strenge til Firefox Monitor

### ISSUE THREAD

**Issue by jakobkappel** [MozillaDanmark/mozilla-dk#1035]
https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?status=unreviewed&string=243934

Jeg har oversat "Email mask" med "email-alias", men det er nok ikke lige nemt at afkode for alle. Selvom jeg godt kan forstå tanken bag at finde på et helt nyt begreb, så ved jeg ikke rigtigt, om det vil fungere på dansk. 

Forslag er med andre ord mere end velkomne :)

**Comment by Joergen** [comment]
Lidt omskrivning af de to strenge? Jeg har teget Jakobs forslag med her til sammenligning:
Shopping with Email Masks-> Handl ind med email-alias'er ->
Maskér din mailadresse, når du handler ind

Use an email mask whenever you shop online. Get the confirmation sent to your real email and then easily turn the mask off anytime later. -> Brug et email-alias, når du handler på nettet. Få bekræftelsen sendt til din rigtige mailadresse, og deaktiver nemt alias'et, når det passer dig. ->
Maskér din mailadresse, når du handler på nettet. Få bekræftelsen sendt til din rigtige mailadresse, og deaktiver nemt maskeringen, når det passer dig.

**Comment by Joergen** [comment]
Ak. Jeg havde ikke set, at begrebet blev anvendt i flere af reklamerne.

**Comment by Joergen** [comment]
Jeg er ikke begejstret for "email-alias". Så her er forslag, hvor jeg har benyttet "maskering" i stedet for.

Shopping with Email Masks->
Handl ind med email-alias'er ->
Maskér din mailadresse, når du handler ind

Use an email mask whenever you shop online. Get the confirmation sent to your real email and then easily turn the mask off anytime later. ->
Brug et email-alias, når du handler på nettet. Få bekræftelsen sendt til din rigtige mailadresse, og deaktiver nemt alias'et, når det passer dig. ->
Maskér din mailadresse, når du handler på nettet. Få bekræftelsen sendt til din rigtige mailadresse, og deaktiver nemt maskeringen, når det passer dig.

Instantly make a custom email mask anywhere and everywhere you go! ->
Lav hurtigt et tilpasset email-alias, uanset hvor du er. ->
Maskér hurtigt din mailadresse uanset hvor du er.

Use your email mask when you want to privately sign in to your favorite coffee shop or public Wi-Fi. ->
Brug dit email-alias, når du vil logge ind privat på din yndlingscafé eller et offentligt wi-fi.->
Maskér din mailadresse, når du vil logge ind privat på din yndlingscafé eller et offentligt wi-fi.

Share a custom email mask for in-store shopping receipts without sharing your real email -> Brug et tilpasset email-alias til at få kvitteringer i butikker - uden at dele din rigtige mailadresse. -> Brug en maskeret mailadresse til til modtagelse af kvitteringer fra butikker - uden at dele din rigtige mailadresse

No matter where you are, create a custom email mask in seconds for anything you want to do ->
Opret tilpassede email-alias'er lynhurtigt, uanset hvor du er. ->
Maskér lynhurtigt din mailadresse, uanset hvor du er.

Before you complete that next signup, use an email mask instead of your real one to protect your info and keep control over your inbox ->
Brug et email-alias for at beskytte dine oplysninger og behold kontrollen over din indbakke, næste gang du skal oprette dig som bruger et sted ->
Maskér din mailadresse for at beskytte dine oplysninger og behold kontrollen over din indbakke, næste gang du skal oprette dig som bruger et sted.

Use an email mask ->
Brug et email-alias ->
Maskér din mailadresse

**Comment by jakobkappel** [comment]
God løsning, @Joergen

Jeg har lavet nye forslag til strengene ovenfor.

**Comment by Joergen** [comment]
2 stk. https://pontoon.mozilla.org/da/firefox-monitor-website/all-resources/?status=unreviewed&string=243933
