### ISSUE TITLE
[KORREKTUR]: 107 strenge til Thunderbird - deadline 30/6

### ISSUE THREAD

**Issue by Pokersut** [MozillaDanmark/mozilla-dk#1133]
107 strenge klar til korrektur: https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=unreviewed

Der er deadline 30. juni.

Der er en del strenge som har to oversættelsesbokse (ental/flertal), men kun én originalstreng - som typisk står i flertal. Ved de fleste har jeg selv lavet en entalsstreng, men denne her giver ikke mening at sætte i ental, så den har jeg ladet stå tom: "The { $count } recipients in To and Cc will see each other’s address. You can avoid disclosing recipients by using Bcc instead."

**Comment by Joergen** [comment]
Jeg kontaktede Flod på Matrix m.h.t. strengene , hvor der er to inputfelter på dansk, men kun en streng i kilden.
Her er hans svar:
That's because the English string is set up as a plural (to trigger the UI in Pontoon), and it's only used for > 1, so the one case is empty

```
about-addressbook-confirm-remove-contacts-multi =
    { $count ->
       *[other] Are you sure you want to remove these { $count } contacts from { $list }?
    }
```

If your locale follows the same plural rules as English, you can switch to FTL advanced mode and only translate other, or even translate the flattened string (without variants and selector)

`about-addressbook-confirm-remove-contacts-multi = Are you sure you want to remove these { $count } contacts from { $list }?`

(this seems cumbersome for a locale like Danish or Italian, with same rule as English, but it's crucial for any other locale with more complex plural rules)

The first translation is correct

```
about-addressbook-confirm-remove-contacts-multi =
    { $count ->
        [one] Er du sikker på, du ønsker at fjerne denne kontakt fra { $list }?
       *[other] Er du sikker på, du ønsker at fjerne disse { $count } kontakter fra { $list }?
    }
```

The one case will just not be used.

Jeg kan godt godkende strengene, selvom dele af indholdet aldrig vil blive brugt. Jeg kan også klikke på FTL og erstatte 

```
about-addressbook-confirm-remove-contacts-multi =
    { $count ->
        [one] Er du sikker på, du ønsker at fjerne denne kontakt fra { $list }?
       *[other] Er du sikker på, du ønsker at fjerne disse { $count } kontakter fra { $list }?
    }
```
med

`about-addressbook-confirm-remove-contacts-multi = Er du sikker på, du ønsker at fjerne disse { $count } kontakter fra { $list }?`

Hvad foretrækker du/I @Pokersut og @jakobkappel ? Som oversætter kan man spare tid, hvis man ikke skal opfinde oversættelser til strenge, der reelt ikke findes. Det problem kan løses med FTL.
Strengen i eksemplet er https://pontoon.mozilla.org/da/thunderbird/all-resources/?search=about-addressbook-confirm-remove-contacts-multi&status=unreviewed&string=281183

**Comment by jakobkappel** [comment]
I den konkrete situation er det nok hurtigst at klikke FTL og oversætte som "flattened" - altså én streng frem for to. Men spørgsmålet er, om det er så tilpas ofte forekommende, at man husker på det? 

Det er sært, at de har gjort sådan. Man skulle jo tro, at det samlede tidsforbrug havde været mindre, hvis det kun var op til oversættere til sprog med eksotiske regler for flertal at forholde sig til det. Men der er sikkert et eller andet, jeg ikke kan se.

**Comment by Pokersut** [comment]
Jeg foretrækker nok at beholde det almindelige interface og så enten lade entals-feltet stå tomt eller finde på en streng. Som jeg forstår det, gør det ikke noget at lade feltet stå tomt?

**Comment by Joergen** [comment]
> Jeg foretrækker nok at beholde det almindelige interface og så enten lade entals-feltet stå tomt eller finde på en streng. Som jeg forstår det, gør det ikke noget at lade feltet stå tomt?

Der er frit valg. Men nu ved vi, at det kan forekomme, og at vi ikke behøver at kreere den manglende streng selv

**Comment by Joergen** [comment]
Jeg har lavet ændringsforslag: https://pontoon.mozilla.org/da/thunderbird/all-resources/?status=unreviewed&string=279187
Jeg har tilføjet kommentarer til nogle af forslagene.
Der er en del strenge, hvor jeg har ændret oversættelsen af "passphrases" fra bl.a "kodefraser" og "adgangsfraser" til "adgangsudtryk". Vi har tidligere oversat det med "adgangsudtryk" i Thunderbird. Ms bruger også den oversættelse.

**Comment by Pokersut** [comment]
Tak for gode forslag, @Joergen
